name: Auto Deploy Go API

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸš€ Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 45.144.166.252
          port: 46600
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/go-api/main-webbase
            git pull origin main
            go build -o app .
            pm2 restart go-api2
